DROP TABLE meansflows IF EXISTS;
DROP TABLE users_roles IF EXISTS;
DROP TABLE users_budgets IF EXISTS;
DROP TABLE budgets IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;



CREATE TABLE users
(							
  id                          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  creation_date               TIMESTAMP  DEFAULT now(),
  last_update                 TIMESTAMP,
  user_name                   VARCHAR(255)         NOT NULL,
  email                       VARCHAR(255)         NOT NULL,
  password                    VARCHAR(255)         NOT NULL,
  user_icon                   BLOB,
  enabled                     BOOLEAN   DEFAULT TRUE,
);
CREATE UNIQUE INDEX unique_email ON users (email);


CREATE TABLE users_roles
(
  user_id          		      INTEGER NOT NULL,
  role            		      VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX user_roles_idx ON users_roles (user_id, role);


CREATE TABLE budgets (
  id                          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  creation_date               TIMESTAMP  DEFAULT now(),
  last_update             	  TIMESTAMP,
  budget_name                 VARCHAR(255) NOT NULL,
  budget_creator_id           INTEGER NOT NULL,
  initial_budget_amount       INTEGER,
  budget_per_day              INTEGER,
  description                 VARCHAR(255) NOT NULL,
  FOREIGN KEY (budget_creator_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX budget_user_idx ON budgets (budget_creator_id, budget_name);

-- many to many relationship, additional table
CREATE TABLE users_budgets (
  user_id                     INTEGER NOT NULL,
  budget_id                   INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (budget_id) REFERENCES budgets (id) ON DELETE CASCADE,
);
CREATE UNIQUE INDEX users_budgets_idx ON users_budgets (user_id, budget_id);


CREATE TABLE meansflows (
  id                          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  creation_date               TIMESTAMP DEFAULT now(),
  last_update                 TIMESTAMP,
  description                 VARCHAR(255) NOT NULL,
  operation_date_time         TIMESTAMP DEFAULT now() NOT NULL,
  amount                      INTEGER NOT NULL,
  budget_id           	      INTEGER NOT NULL,
  user_id	                  INTEGER,
  goods_type                  VARCHAR(255) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
  FOREIGN KEY (budget_id) REFERENCES budgets (id) ON DELETE CASCADE
);
